// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
import Flutter

/// Generated class from Pigeon.

/// Generated class from Pigeon that represents data sent in messages.
struct FitDateRange {
  var fromDate: String? = nil
  var toDate: String? = nil

  static func fromMap(_ map: [String: Any?]) -> FitDateRange? {
    let fromDate = map["fromDate"] as? String 
    let toDate = map["toDate"] as? String 

    return FitDateRange(
      fromDate: fromDate,
      toDate: toDate
    )
  }
  func toMap() -> [String: Any?] {
    return [
      "fromDate": fromDate,
      "toDate": toDate
    ]
  }
}

private class FitApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return FitDateRange.fromMap(self.readValue() as! [String: Any])      
      default:
        return super.readValue(ofType: type)
      
    }
  }
}
private class FitApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FitDateRange {
      super.writeByte(128)
      super.writeValue(value.toMap())
    } else {
      super.writeValue(value)
    }
  }
}

private class FitApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FitApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FitApiCodecWriter(data: data)
  }
}

class FitApiCodec: FlutterStandardMessageCodec {
  static let shared = FitApiCodec(readerWriter: FitApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FitApi {
  func getSteps(dateRange: FitDateRange, completion: @escaping (Int32) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FitApiSetup {
  /// The codec used by FitApi.
  static var codec: FlutterStandardMessageCodec { FitApiCodec.shared }
  /// Sets up an instance of `FitApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FitApi?) {
    let getStepsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.FitApi.getSteps", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStepsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dateRangeArg = args[0] as! FitDateRange
        api.getSteps(dateRange: dateRangeArg) { result in
          reply(wrapResult(result))
        }
      }
    } else {
      getStepsChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [String: Any?] {
  return ["result": result]
}

private func wrapError(_ error: FlutterError) -> [String: Any?] {
  return [
    "error": [
      "code": error.code,
      "message": error.message,
      "details": error.details
    ]
  ]
}
