// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "FitInterface.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface FitDateRange ()
+ (FitDateRange *)fromMap:(NSDictionary *)dict;
+ (nullable FitDateRange *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FitDateRange
+ (instancetype)makeWithFromDate:(nullable NSString *)fromDate
    toDate:(nullable NSString *)toDate {
  FitDateRange* pigeonResult = [[FitDateRange alloc] init];
  pigeonResult.fromDate = fromDate;
  pigeonResult.toDate = toDate;
  return pigeonResult;
}
+ (FitDateRange *)fromMap:(NSDictionary *)dict {
  FitDateRange *pigeonResult = [[FitDateRange alloc] init];
  pigeonResult.fromDate = GetNullableObject(dict, @"fromDate");
  pigeonResult.toDate = GetNullableObject(dict, @"toDate");
  return pigeonResult;
}
+ (nullable FitDateRange *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [FitDateRange fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"fromDate" : (self.fromDate ?: [NSNull null]),
    @"toDate" : (self.toDate ?: [NSNull null]),
  };
}
@end

@interface FitApiCodecReader : FlutterStandardReader
@end
@implementation FitApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FitDateRange fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FitApiCodecWriter : FlutterStandardWriter
@end
@implementation FitApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FitDateRange class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FitApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FitApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FitApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FitApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FitApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FitApiCodecReaderWriter *readerWriter = [[FitApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FitApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FitApi.getSteps"
        binaryMessenger:binaryMessenger
        codec:FitApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getStepsDateRange:completion:)], @"FitApi api (%@) doesn't respond to @selector(getStepsDateRange:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FitDateRange *arg_dateRange = GetNullableObjectAtIndex(args, 0);
        [api getStepsDateRange:arg_dateRange completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
