// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FitDateRange;

@interface FitDateRange : NSObject
+ (instancetype)makeWithFromDate:(nullable NSString *)fromDate
    toDate:(nullable NSString *)toDate;
@property(nonatomic, copy, nullable) NSString * fromDate;
@property(nonatomic, copy, nullable) NSString * toDate;
@end

/// The codec used by FitApi.
NSObject<FlutterMessageCodec> *FitApiGetCodec(void);

@protocol FitApi
- (void)getStepsDateRange:(FitDateRange *)dateRange completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FitApi> *_Nullable api);

NS_ASSUME_NONNULL_END
