// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HealthDateRange;

@interface HealthDateRange : NSObject
+ (instancetype)makeWithFromDate:(nullable NSString *)fromDate
    toDate:(nullable NSString *)toDate;
@property(nonatomic, copy, nullable) NSString * fromDate;
@property(nonatomic, copy, nullable) NSString * toDate;
@end

/// The codec used by HealthApi.
NSObject<FlutterMessageCodec> *HealthApiGetCodec(void);

@protocol HealthApi
- (void)getStepsDateRange:(HealthDateRange *)dateRange completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void HealthApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HealthApi> *_Nullable api);

NS_ASSUME_NONNULL_END
