// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "HealthInterface.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface HealthDateRange ()
+ (HealthDateRange *)fromMap:(NSDictionary *)dict;
+ (nullable HealthDateRange *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation HealthDateRange
+ (instancetype)makeWithFromDate:(nullable NSString *)fromDate
    toDate:(nullable NSString *)toDate {
  HealthDateRange* pigeonResult = [[HealthDateRange alloc] init];
  pigeonResult.fromDate = fromDate;
  pigeonResult.toDate = toDate;
  return pigeonResult;
}
+ (HealthDateRange *)fromMap:(NSDictionary *)dict {
  HealthDateRange *pigeonResult = [[HealthDateRange alloc] init];
  pigeonResult.fromDate = GetNullableObject(dict, @"fromDate");
  pigeonResult.toDate = GetNullableObject(dict, @"toDate");
  return pigeonResult;
}
+ (nullable HealthDateRange *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [HealthDateRange fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"fromDate" : (self.fromDate ?: [NSNull null]),
    @"toDate" : (self.toDate ?: [NSNull null]),
  };
}
@end

@interface HealthApiCodecReader : FlutterStandardReader
@end
@implementation HealthApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [HealthDateRange fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface HealthApiCodecWriter : FlutterStandardWriter
@end
@implementation HealthApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[HealthDateRange class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface HealthApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HealthApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HealthApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HealthApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HealthApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    HealthApiCodecReaderWriter *readerWriter = [[HealthApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void HealthApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HealthApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HealthApi.getSteps"
        binaryMessenger:binaryMessenger
        codec:HealthApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getStepsDateRange:completion:)], @"HealthApi api (%@) doesn't respond to @selector(getStepsDateRange:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HealthDateRange *arg_dateRange = GetNullableObjectAtIndex(args, 0);
        [api getStepsDateRange:arg_dateRange completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
