import 'package:caravaneering/model/save_keys.dart';
import 'package:global_configuration/global_configuration.dart';

class ItemDetails{
  static const String horseKey = SaveKeysV1.horses;
  static const String cartKey = SaveKeysV1.carts;
  static const String petKey = SaveKeysV1.pets;

  static const String coins = "coin";
  static const String gems = "gem";

  static const String coinImagePath = "assets/images/UI/CoinIcon.png";
  static const String gemImagePath = "assets/images/UI/GemIcon.png";

  static List<dynamic> startingHorses = Map.from(GlobalConfiguration().getValue("stateDefaults"))[SaveKeysV1.equippedHorses];
  static List<dynamic> startingCarts = Map.from(GlobalConfiguration().getValue("stateDefaults"))[SaveKeysV1.equippedCarts];
  static List<dynamic> startingPets = Map.from(GlobalConfiguration().getValue("stateDefaults"))[SaveKeysV1.equippedPets];

  static const Map<String, Map<String, dynamic>> items = {
    "horse-brown": {
      "key": "horse-brown",
      "name": "Brown horse",
      "type": horseKey,
      "cost": 0,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-brown.png",
      "description": "This is the starter horse",
    },
    "horse-tan": {
      "key": "horse-tan",
      "name": "Tan horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-tan.png",
      "description": "The best horse money can buy!",
    },
    "horse-black": {
      "key": "horse-black",
      "name": "Black horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-black.png",
      "description": "The best horse money can buy!",
    },
    "horse-grey": {
      "key": "horse-grey",
      "name": "Grey horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-grey.png",
      "description": "The best horse money can buy!",
    },
    "horse-cream": {
      "key": "horse-cream",
      "name": "Cream horse",
      "type": horseKey,
      "cost": 100,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-cream.png",
      "description": "The best horse money can buy!",
    },
    "horse-red": {
      "key": "horse-red",
      "name": "Red horse",
      "type": horseKey,
      "cost": 100,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-red.png",
      "description": "The best horse money can buy!",
    },
    "horse-white": {
      "key": "horse-white",
      "name": "White horse",
      "type": horseKey,
      "cost": 1000,
      "purchaseCurrency": coins,
      "location": "assets/images/items/horse-white.png",
      "description": "The best horse money can buy!",
    },
    "horse-green": {
      "key": "horse-green",
      "name": "Green horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": gems,
      "location": "assets/images/items/horse-green.png",
      "description": "The best horse money can buy!",
    },
    "horse-blue": {
      "key": "horse-blue",
      "name": "Blue horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": gems,
      "location": "assets/images/items/horse-blue.png",
      "description": "The best horse money can buy!",
    },
    "horse-purple": {
      "key": "horse-purple",
      "name": "Purple horse",
      "type": horseKey,
      "cost": 50,
      "purchaseCurrency": gems,
      "location": "assets/images/items/horse-purple.png",
      "description": "The best horse money can buy!",
    },
    "cart_flat": {
      "key": "cart_flat",
      "name": "Cart level 1",
      "type": cartKey,
      "cost": 10,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Flat.png",
      "locationAnimated": "assets/images/items/CartFlat.png",
      "description": "Guess this counts as a cart...",
    },
    "cart_sticks": {
      "key": "cart_sticks",
      "name": "Stick Cart",
      "type": cartKey,
      "cost": 50,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Sticks.png",
      "locationAnimated": "assets/images/items/CartSticks.png",
      "description": "Best cart money can buy!",
    },
    "cart_sticks_pine": {
      "key": "cart_sticks_pine",
      "name": "Pine Stick Cart",
      "type": cartKey,
      "cost": 100,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Sticks_Pine.png",
      "locationAnimated": "assets/images/items/CartSticksPine.png",
      "description": "Best cart money can buy!",
    },
    "cart_plank": {
      "key": "cart_plank",
      "name": "Plank Cart",
      "type": cartKey,
      "cost": 200,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Planks.png",
      "locationAnimated": "assets/images/items/CartPlanks.png",
      "description": "Best cart money can buy!",
    },
    "cart_planks_pine": {
      "key": "cart_planks_pine",
      "name": "Pine Plank Cart",
      "type": cartKey,
      "cost": 400,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Planks_Pine.png",
      "locationAnimated": "assets/images/items/CartPlanksPine.png",
      "description": "Best cart money can buy!",
    },
    "cart-tarp": {
      "key": "cart-tarp",
      "name": "Tarp Cart",
      "type": cartKey,
      "cost": 600,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Tarp.png",
      "locationAnimated": "assets/images/items/CartTarp.png",
      "description": "Best cart money can buy!",
    },
    "cart-purple": {
      "key": "cart-purple",
      "name": "Purple cart",
      "type": cartKey,
      "cost": 1000,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Tarp_Purple.png",
      "locationAnimated": "assets/images/items/CartTarpPurple.png",
      "description": "Best cart money can buy!",
    },
    "cart-blue": {
      "key": "cart-blue",
      "name": "Blue cart",
      "type": cartKey,
      "cost": 1000,
      "purchaseCurrency": coins,
      "location": "assets/images/items/Cart_Tarp_Blue.png",
      "locationAnimated": "assets/images/items/CartTarpNavy.png",
      "description": "Best cart money can buy!",
    },
    "cart-red": {
      "key": "cart-red",
      "name": "Red cart",
      "type": cartKey,
      "cost": 400,
      "purchaseCurrency": gems,
      "location": "assets/images/items/Cart_Tarp_Red.png",
      "locationAnimated": "assets/images/items/CartTarpRed.png",
      "description": "Best cart money can buy!",
    },
    "cart-aqua": {
      "key": "cart-aqua",
      "name": "Aqua cart",
      "type": cartKey,
      "cost": 400,
      "purchaseCurrency": gems,
      "location": "assets/images/items/Cart_Tarp_Aqua.png",
      "locationAnimated": "assets/images/items/CartTarpAqua.png",
      "description": "Best cart money can buy!",
    },
    "cat-white": {
      "key": "cat-white",
      "name": "White Cat",
      "type": petKey,
      "cost": 200,
      "purchaseCurrency": coins,
      "location": "assets/images/items/cat-white.png",
      "description": "A brand new pet for your caravan!",
    },
    "cat-black": {
      "key": "cat-black",
      "name": "Black Cat",
      "type": petKey,
      "cost": 200,
      "purchaseCurrency": coins,
      "location": "assets/images/items/cat-black.png",
      "description": "A brand new pet for your caravan!",
    },
    "cat-orange": {
      "key": "cat-orange",
      "name": "Tabby Cat",
      "type": petKey,
      "cost": 400,
      "purchaseCurrency": coins,
      "location": "assets/images/items/cat-orange.png",
      "description": "A brand new pet for your caravan!",
    },
    "dog-brown": {
      "key": "dog-brown",
      "name": "Brown Dog",
      "type": petKey,
      "cost": 200,
      "purchaseCurrency": coins,
      "location": "assets/images/items/dog-brown.png",
      "description": "A brand new pet for your caravan!",
    },
    "dog-yellow": {
      "key": "dog-yellow",
      "name": "Yellow Dog",
      "type": petKey,
      "cost": 400,
      "purchaseCurrency": coins,
      "location": "assets/images/items/dog-yellow.png",
      "description": "A brand new pet for your caravan!",
    },
    "dog-white": {
      "key": "dog-white",
      "name": "White Dog",
      "type": petKey,
      "cost": 200,
      "purchaseCurrency": coins,
      "location": "assets/images/items/dog-white.png",
      "description": "A brand new pet for your caravan!",
    },
    "bird-pink": {
      "key": "bird-pink",
      "name": "Pink Cockatoo",
      "type": petKey,
      "cost": 1000,
      "purchaseCurrency": coins,
      "location": "assets/images/items/bird-pink.png",
      "description": "A brand new pet for your caravan!",
    },
    "bird-blue": {
      "key": "bird-blue",
      "name": "Blue Macaw",
      "type": petKey,
      "cost": 1000,
      "purchaseCurrency": coins,
      "location": "assets/images/items/bird-blue.png",
      "description": "A brand new pet for your caravan!",
    },
    "dragon": {
      "key": "dragon",
      "name": "Purple Dragon",
      "type": petKey,
      "cost": 500,
      "purchaseCurrency": gems,
      "location": "assets/images/items/dragon.png",
      "description": "A dragon!!!",
    }
  };
}